# Generated by Django 4.1.6 on 2023-03-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'customer_otp',
                'db_table': 'customer_otp',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(unique=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=254, null=True, unique=True)),
                ('email_id_verified', models.BooleanField(default=False)),
                ('subscribe_for_updates', models.BooleanField(default=True)),
                ('display_picture', models.UUIDField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10)),
                ('customer_id', models.UUIDField()),
                ('device_id', models.UUIDField()),
                ('token', models.UUIDField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('keep_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customer_token',
                'managed': True,
                'unique_together': {('mobile_number', 'device_id', 'token')},
            },
        ),
    ]
