# Generated by Django 4.1.6 on 2023-03-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='display_picture',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
