# Generated by Django 4.1.6 on 2023-04-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_customers', '0001_initial'),
        ('apps_employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('wedding', 'Wedding'), ('engagement', 'Engagement'), ('family', 'Family'), ('party', 'Party'), ('portrait', 'Portrait'), ('event', 'Event'), ('maternity', 'Maternity'), ('real_estate', 'Real Estate'), ('graduation', 'Graduation'), ('team_and_office', 'Team and office'), ('product', 'Product'), ('modelling', 'Modelling'), ('food', 'Food'), ('vehicles', 'Vehicles'), ('baby', 'Baby'), ('kids', 'Kids'), ('sport', 'Sport'), ('pet', 'Pet'), ('religious', 'Religious'), ('short_film', 'Short Film'), ('other', 'Other')], max_length=20)),
                ('event_description', models.CharField(max_length=500, null=True)),
                ('event_date', models.DateField()),
                ('event_start_time', models.TimeField()),
                ('event_duration', models.IntegerField()),
                ('event_postal_code', models.CharField(max_length=7)),
                ('event_city', models.CharField(max_length=50)),
                ('event_address', models.CharField(max_length=150)),
                ('event_latitude', models.DecimalField(decimal_places=12, max_digits=15, null=True)),
                ('event_longitude', models.DecimalField(decimal_places=12, max_digits=15, null=True)),
                ('lifecycle', models.JSONField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_customers.customers')),
            ],
            options={
                'verbose_name': 'bookings',
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_requested_time', models.DateTimeField(null=True)),
                ('payment_received_time', models.DateTimeField(null=True)),
                ('transaction_reference_id', models.CharField(max_length=200, null=True)),
                ('reversed', models.BooleanField(default=False)),
                ('dispute', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_bookings.bookings')),
            ],
            options={
                'verbose_name': 'transactions',
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.UUIDField(unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('service', models.CharField(choices=[('photography', 'photography'), ('videography', 'videography'), ('drone_photography', 'drone_photography'), ('photo_editing', 'photo_editing'), ('video_editing', 'video_editing')], max_length=20)),
                ('lifecycle', models.JSONField(null=True)),
                ('retired', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_bookings.bookings')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_employees.employees')),
            ],
            options={
                'verbose_name': 'services',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_code', models.CharField(max_length=10, null=True)),
                ('other_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_id', models.UUIDField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps_bookings.services')),
            ],
            options={
                'verbose_name': 'service_invoice',
                'db_table': 'service_invoice',
            },
        ),
        migrations.CreateModel(
            name='EmployeePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_employees.employees')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_bookings.services')),
            ],
            options={
                'verbose_name': 'employee_preference',
                'db_table': 'employee_preference',
            },
        ),
    ]
