# Generated by Django 4.2 on 2023-04-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=100)),
                ('mime_type', models.CharField(max_length=25)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_bookings.services')),
            ],
            options={
                'verbose_name': 'files',
                'db_table': 'files',
            },
        ),
    ]
