# Generated by Django 4.1.6 on 2023-03-19 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='lifecycle',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
