# Generated by Django 4.1.6 on 2023-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_bookings', '0002_services_created_time_services_lifecycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='event_latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='event_longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
    ]
