# Generated by Django 5.0.3 on 2024-04-01 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_bookings', '0006_alter_files_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.UUIDField(default=uuid.UUID('07fb04f4-fbb5-4bd8-a826-be9bcfdafa1a')),
        ),
    ]
