# Generated by Django 5.0.3 on 2024-04-01 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_bookings', '0007_alter_files_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.UUIDField(default=uuid.UUID('f923d7e5-9e7a-45d6-81f7-7f848a10db0b')),
        ),
    ]
