# Generated by Django 5.0.3 on 2024-04-01 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_bookings', '0008_alter_files_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.UUIDField(default=uuid.UUID('cde42ee7-b6bb-48b9-8169-1ef65c519f32')),
        ),
    ]
