# Generated by Django 5.0.3 on 2024-04-07 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_bookings', '0010_alter_files_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.UUIDField(default=uuid.UUID('6c2be85c-339f-4e0a-b3eb-7f9ba191c727')),
        ),
    ]
