# Generated by Django 5.0.3 on 2024-04-21 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_bookings', '0011_bookings_published_alter_files_file_id'),
        ('apps_employees', '0003_employeebankdetails_employees_bank_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='closed_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='employee_backup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_backup', to='apps_employees.employees'),
        ),
        migrations.AddField(
            model_name='services',
            name='retired_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.UUIDField(default=uuid.UUID('01656446-a092-4e23-add4-13e60fec8380')),
        ),
        migrations.AlterField(
            model_name='services',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='apps_employees.employees'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service',
            field=models.CharField(choices=[('photography', 'photography'), ('videography', 'videography'), ('drone', 'drone'), ('photo_editing', 'photo_editing'), ('video_editing', 'video_editing')], max_length=20),
        ),
    ]
