# Generated by Django 4.1.6 on 2023-03-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='profile_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='display_picture',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id_proof_back',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id_proof_front',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
