# Generated by Django 4.1.6 on 2023-05-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_employees', '0002_employees_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_details_id', models.UUIDField(unique=True)),
                ('bank', models.CharField(max_length=80)),
                ('branch', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=20)),
                ('account_holder', models.CharField(max_length=60)),
                ('mobile_number', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'employee_bank_details',
                'db_table': 'employee_bank_details',
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='bank_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_employees.employeebankdetails'),
        ),
    ]
