# Generated by Django 4.1.6 on 2023-03-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_employees', '0002_employees_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='id_proof_type',
            field=models.CharField(choices=[('aadhar', 'aadhar'), ('passport', 'passport'), ('drivinglicence', 'drivinglicence'), ('votersid', 'votersid')], max_length=15, null=True),
        ),
    ]
