# Generated by Django 4.1.6 on 2023-03-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_employees', '0004_alter_employees_id_proof_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='base_location_latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='base_location_longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
    ]
